---
- name: add a login to our Tomcat server
  template:
    src: templates/tomuser.j2
    dest: /opt/tomcat/conf/tomcat-users.xml



- name: access to the Manager 
  template:
    src: templates/managercontext.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: access to the  host Manager 
  template:
    src: templates/hostmanagercontext.j2
    dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml